[tox]
envlist = test, lint, docs

[testenv]
skip_install = true

[testenv:test]
deps = 
    pytest
    pytest-cov
commands = pytest -q --cov=src --tb=no tests/

[testenv:lint]
deps = ruff
commands = ruff check src/

[testenv:docs]
deps = pydocstyle
commands = pydocstyle src/
